// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkjvfltnmfkromjnlnor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtranZmbHRubWZrcm9tam5sbm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjU2ODMsImV4cCI6MjA1ODcwMTY4M30.nIv4aY5FFrEuO334YIcxqIp_SnPYbGlD6NVhdSpf2-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);